### PR TITLE
make documentation more accessible

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by soenkehahn** [comment]
I realized that the haddock rendering of the tutorial module (`Generics.Eot.Tutorial`, for example here: https://www.stackage.org/haddock/lts-11.3/generics-eot-0.2.1.2/Generics-Eot-Tutorial.html) ended up without the tutorial comments. Therefore I thought it was actually harmful to include that module in the package -- because it might prevent people from finding the real tutorial (here: http://generics-eot.readthedocs.io/en/stable/tutorial.html). Therefore I removed that module from the exposed modules of the package.

This PR also includes various other tweaks that makes the documentation hopefully more discoverable.

CC: @gwils

**Comment by soenkehahn** [comment]
I still have to remove the `markdown-unlit` dependency from the library section of the package.

**Comment by gwils** [comment]
:+1: 
Looks good to me, once the markdown-unlit dependency is dropped.

**Comment by soenkehahn** [comment]
@gwils: Thanks a lot for reviewing. I removed the `markdown-unlit` dependency and also your changes involving `build-tool-depends`, since they are not needed anymore to use `generics-eot` as a dependency with `cabal new-build`. Will merge as soon as CI goes green.

**Pull request merged**
